using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.UI.Windows.ImperialInfoWindow;


[GenerateTypedNameReferences]
public sealed partial class ImperialInfoWindow : BaseImperialWindow.BaseImperialWindow
{
    public event Action? OnSubmitButtonPressed;

    public ImperialInfoWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SubmitButton.OnPressed += (_) => OnSubmitButtonPressed?.Invoke();
    }
}
