using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Imperial.UI.Windows.RedirectWindow;


[GenerateTypedNameReferences]
public sealed partial class RedirectWindow : BaseImperialWindow.BaseImperialWindow
{
    [Dependency] private readonly IUriOpener _uriOpener = default!;

    public string? UriRedirect;


    public RedirectWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InfoText.Text = Loc.GetString("imperial-pass-ui-redirect-info-text");
    }

    public RedirectWindow(string redirectUri)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        InfoText.Text = Loc.GetString("imperial-pass-ui-redirect-info-text");
        RedirectLink.Text = redirectUri;
        RedirectLink.CursorPosition = 0;

        RedirectButton.OnPressed += (_) => _uriOpener.OpenUri(redirectUri);
        CancelButton.OnPressed += (_) => Close();
    }
}
